version: 2
sphinx:
    configuration: doc/conf.py
    builder: html

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
      python: "3.10"


formats: []
python:
    # install doc/requirements at the end to make sure pillow 9.5.0 is used
    # also needs sphinx <7
    install:
        - method: pip
          path: .
        - requirements: doc/requirements.txt

